### ISSUE TITLE
wondering if it's possible to make it work with YouCompleteMe

### ISSUE THREAD

**Issue by Aaron2Ti** [clausreinke/typescript-tools#27]
https://github.com/Valloric/YouCompleteMe

**Comment by SirVer** [comment]
I just installed this and it *does* work out of the box with YouCompleteMe. To make it trigger automatically after a "." I added a small blib to my vimrc.

~~~vim
if !exists("g:ycm_semantic_triggers")
   let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers['typescript'] = ['.']
~~~

I suggest adding that into this ftplugin as it is save even if people do not use YCM.

My complete setup using [YouCompleteMe](https://github.com/Valloric/YouCompleteMe), [typescript-tools](https://github.com/clausreinke/typescript-tools), [typescript-vim](https://github.com/leafgarland/typescript-vim), and [NeoBundle](https://github.com/Shougo/neobundle.vim) as my plugin manager looks like this:

~~~vim
NeoBundle 'clausreinke/typescript-tools'
NeoBundle 'leafgarland/typescript-vim'
NeoBundle 'Valloric/YouCompleteMe'

if !exists("g:ycm_semantic_triggers")
   let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers['typescript'] = ['.']
~~~

Now opening a `.ts` file and running `:TSSstarthere` gives me nice completion and syntax highlighting. Fabulous example of technology just fitting together nicely, thanks to everybody involved for a Job well done!

**Comment by dani-h** [comment]
@SirVer Thanks for the tip! Do you have any idea on how I can get paramteres to pop up?

**Comment by SirVer** [comment]
@dani-h I do not understand the question. With my setup described above, the parameters pop up after each '.' automatically. However there seems to be no support for typescript 1.4 features in this repo yet, so sometimes it breaks down.

**Comment by clausreinke** [comment]
@SirVer TypeScript 1.4 support (or rather: v1.5, the current github version)  is available in a branch `testing_ts1.4` - see also #39 . Note that a few things have changed, and may still change, as we follow upstream developments (hence the testing branch;-).

**Comment by SirVer** [comment]
@clausreinke I felt that was WIP. I tried to use it with a small angular toy project and it failed to pick up the definitions from https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts most of the time (it only worked once and it threw an error message and stopped working later). Do you want bug reports for that branch?

**Comment by clausreinke** [comment]
@SirVer yes, please - the testing branch is far enough along that bug reports are welcome. I hope to fix the ones I know about next week.
