### ISSUE TITLE
How I can configure it to target ES5 when checking for errors?

### ISSUE THREAD

**Issue by hippich** [clausreinke/typescript-tools#41]
I am getting a lot of:

"TS1056: Accessors are only available when targeting ECMAScript 5 and higher."

And was wondering if there is a way to configure it to use ES5 standard?

**Comment by clausreinke** [comment]
If I recall correctly, I used ES5 as the default target, with no configuration, but it has been a while.

I'm going to spend some time on this project next week anyway, because of #39. Given that TS1.4 has some ES6 capabilities, being able to configure the target sounds like a good idea.

**Comment by clausreinke** [comment]
@hippich can you provide a small test case that shows the error?

**Comment by hippich** [comment]
I got this error with simple test.ts file with the following content:

```
var Something = {
  get name() {
    return 'test';
  }
};
```

**Comment by clausreinke** [comment]
Thanks, that helps: I still see no error, with:
```
$ ../bin/tss --version
v0.3.1-2-g12c88d4

$ ../bin/tss empty.ts <issue-41.script
"loaded c:/javascript/typescript/codeplex/typescript-tools/tests/empty.ts, TSS listening.."
update 5 empty.ts
var Something = {
  get name() {
    return 'test';
  }
};
"updated c:/javascript/typescript/codeplex/typescript-tools/tests/empty.ts, (0/0) errors"
showErrors
[]
```
same if I load directly from file (instead of updating an empty file)

**Comment by hippich** [comment]
Uh, I am so sorry to waste your time on this - it turned out default configuration of Syntastic plugin was throwing it off. Yes, tss seems alright! Thank you!
