### ISSUE TITLE
TSSreferences does not show contents of line in location list

### ISSUE THREAD

**Issue by jomifo** [clausreinke/typescript-tools#45]
TSSreferences does not show contents of line in location list, only filename, line number and column.  

Would be very useful to have contents of line shown.

![image](https://cloud.githubusercontent.com/assets/165533/6353223/0628891c-bc16-11e4-923a-2d40d2df77e7.png)

**Comment by clausreinke** [comment]
Thanks for the reminder - somehow this had dropped from my TODO list. Fixed in testing_ts1.4 branch.
