### ISSUE TITLE
Vim: Showing the file structure in another window

### ISSUE THREAD

**Issue by dani-h** [clausreinke/typescript-tools#48]
I was wondering if something similar to the TagList plugin could be implemented. I know that the functionality is already there using ```:TSSstructure```.

Instead of the navigation menu the list could be shown in a new window to the left/right. Since you already have the types and parameters they could be shown too (something that TagList doesn't do).

![taglist_xp_cmd](https://cloud.githubusercontent.com/assets/5557301/6542867/8119b048-c507-11e4-8189-535522290d0a.gif)
http://vim-taglist.sourceforge.net/images/taglist_xp_cmd.gif

**Comment by clausreinke** [comment]
The idea of plugins is to reuse and compose them, not to reimplement functionality. It would be great to integrate information from typescript-tools with gui from a popular source browsing tool like taglist or tagbar. That integration should happen in a .vimrc, although I'd be happy to link to a blog post or such detailing a solution.

`TSSstructure` is gone, replaced by `TSSnavigation` - the underlying `navigationBarItems` command in `tss` should provide all the information you need. Sadly, plugins like taglist insist on getting their info from `ctags` (I think; also haven't checked tagbar extension mechanism yet).

If you find a source browsing plugin like taglist or tagbar that can be extended in VimScript, please add that info here. I might then look into integration myself, if the browing gui is useful enough.

**Comment by clausreinke** [comment]
Cursory inspection shows that both tagbar and taglist insist on calling external ctag-like programs:-(

**Comment by dani-h** [comment]
:[

**Comment by clausreinke** [comment]
to be continued in clausreinke/typescript-tools.vim#1
