### ISSUE TITLE
split tss and vim into separate repos?

### ISSUE THREAD

**Issue by clausreinke** [clausreinke/typescript-tools#50]
Sometime after the TS1.5 update, we should perhaps split up the repo. So far that hasn't felt urgent, as the single vim-specific file doesn't add weight, and commits (with a few exceptions - oops) tend to be marked and split into vim-specific and general aspects, so can be filtered. Also, the Vim aspect is the part that motivates me to work on the tss part, it provides both a real-world test case and example, and non-Vim users tended to follow their own editor-plugin repos (so only the non-Vim plugin authors were exposed to possibly irrelevant info).

The best argument in favour of a split comes from those following the repo: I'm not sure how well the repo feed can be filtered for non-vim specific info (I've now started adding labels, so you can filter issues by using `-label:vim`). Also, since stars seem to double every year, I'm no longer sure of the audience interests.

Btw, if you're watching here, could you add a quick line to this issue stating whether you're following
- because of the Vim plugin
- because of tss only (what are you using it for? are you a plugin author? please link to your plugin)

**Comment by zlumer** [comment]
I'm following because of tss only. Used it in FlashDevelop plugin 2 years ago. https://github.com/zlumer/fd-ts

**Comment by dani-h** [comment]
I'm watching for both, but I still think it's a good idea to split up the repos.

**Comment by jomifo** [comment]
I'm also watching for both and also tend to think separate repos is a good
idea.

**Comment by eggers** [comment]
I'm watching for vim

**Comment by clausreinke** [comment]
no one has spoken against, so this split is going to happen (I'll deprecate the in-repo vim plugin for the next release).
