### ISSUE TITLE
Angular.d.ts seems to break completion.

### ISSUE THREAD

**Issue by SirVer** [clausreinke/typescript-tools#51]
This is a bug report against the `testing_ts1.4` branch.

Create a single file named `blub.ts` containing one line:

~~~typescript
/// <reference path='libs/angularjs/angular.d.ts' />
~~~

This references https://github.com/borisyankov/DefinitelyTyped/blob/master/angularjs/angular.d.ts which is put into the correct sub directory: `libs/angularjs`. 

Running `:TSSstarthere`: 
~~~
:TSSstarthere
starting TSS, loading client/blub.ts...
['tss', 'client/blub.ts']
"loaded /Users/sirver/Desktop/Programming/rust/web_stack/client/blub.ts, TSS listening.."
Error detected while processing function TSSstart..TSSshowErrors:
line   16:
TSS command processing error: TypeError: undefined is not a function
~~~

This is on a very recent from HEAD build of MacVim.

**Comment by SirVer** [comment]
This bug was created in reference of https://github.com/clausreinke/typescript-tools/issues/27#issuecomment-77776777

**Comment by clausreinke** [comment]
Thanks for the report, but I cannot reproduce that. Using current repos (`git describe --tags` gives `v0.3.1-21-g23e4e09` for typescript-tools and `v1.3-2960-g5556683` for typescript), I only get a bunch of error messages for missing JQuery, which can be silenced by adding that .d.ts, as well.

**Comment by SirVer** [comment]
While figuring out the installed versions on my system I realized that I had a mismatched between my installed `tss` and the `typescript-tools` sha. This lead me to figure out that I forgot to run `npm install -g` after pulls again. Now everything works nicely again. Sorry for the noise!
