### ISSUE TITLE
Doc: showError output

### ISSUE THREAD

**Issue by Phaiax** [clausreinke/typescript-tools#52]
I just discovered that showError["text"] can either be a dict or a string.

Example: https://github.com/Phaiax/ArcticTypescript/issues/34

Maybe you want to update your docs.

**Comment by clausreinke** [comment]
Grmpff. The joys of trying to follow TypeScript APIs - they keep changing all the time. This one changed a month ago, apparently, and the union type prevented type errors:-(

If I understand the change correctly, I'm supposed to follow the message chain and join the texts with EOLs, so no need to change docs or clients.

**Comment by clausreinke** [comment]
ps: would you like me to mention ArcticTypescript in our README, or do you expect to switch to TSserver soon?-)

**Comment by clausreinke** [comment]
on second thought: clients might find it easier if I would convert the nested chains to lists.
Any other plugin authors listening here?

**Comment by Phaiax** [comment]
I plan to switch to TSServer somewhen, but they are doing their own Sublime Plugin with it, so maybe AT will be obsolete someday in the future. But for now the race is going on and I try to get it as stable as I can with typescript-tools, so you can mention AT :D
