### ISSUE TITLE
Error detected while processing function TSSdef

### ISSUE THREAD

**Issue by dani-h** [clausreinke/typescript-tools#54]
When I run TSSdef over a function defined in another file, it occasionally fails. I've also noticed that the autocomplete has given up at this point. I use typescript-tools together with YouCompleteMe. It usually works fine but fails sometimes.

```
Error detected while processing function TSSdef:
line 5:
TSS command processing error: TypeError: Cannot call method 'map' of null
```

Update: Actually it seems like nothing works after updating my plugin through Vundle. I've updated the plugin and the global npm package to the most recent version.

**Comment by clausreinke** [comment]
fixed the main issue.

"nothing works" is not too helpful, though;-) are you sure you've updated to the testing branch versions, not the old npm registry and master versions?
```
$ bin/tss --version
v0.4.4-testing-ts1.4

$ git describe --tags
v0.3.1-36-g405a9ef
```

**Comment by dani-h** [comment]
Well nothing did work and I was unsure if the problem was this or YCM. It seems like testing-ts1.4 works fine, why doesn't the main branch?

Thanks Claus +1
