### ISSUE TITLE
typescript@1.5.0-alpha is now in npm, please upload typescript-tools1.5

### ISSUE THREAD

**Issue by hammerandtongs** [clausreinke/typescript-tools#56]
typescript@1.5.0-alpha is now in npm, please upload typescript-tools1.5

**Comment by MichaelZahar** [comment]
+1

**Comment by clausreinke** [comment]
with the updated dependency, you can easily use
`npm install -g clausreinke/typescript-tools`
for testing purposes (same reference works for dependencies).

**Comment by lazutkin** [comment]
its time to get updated to 1.5-beta

**Comment by clausreinke** [comment]
seems to be merely a matter of relaxing the dependency, as far as I can see.

**Comment by clausreinke** [comment]
oops. actually, I have a whole bunch of unpushed changes pending. See `develop` branch.

**Comment by clausreinke** [comment]
haven't heard any negatives about the `develop` branch, so I've merged the changes into `master`.

**Comment by clausreinke** [comment]
We also have versions matching 1.6, 1.7 and 1.8 now.
