### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by dani-h** [clausreinke/typescript-tools#57]
![tss-crash](https://cloud.githubusercontent.com/assets/5557301/7942946/d06a4bf0-0961-11e5-9ef0-02d87dd9a692.png)

I called :TSSreload in the Neovim-qt client and the plugin crashed. It usually runs smooth in all vim and neovim variants I've used (vim, gvim, nvim, nvim-qt, pynvim). I was defining a custom type and doing `instanceof` checks to find out which type was being passed when it crashed. I'll try to find out exactly what caused it later.

**Comment by clausreinke** [comment]
Any news/info on this? Or can I close it as not-reproducable?

**Comment by dani-h** [comment]
Closed
