### ISSUE TITLE
Error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by mperdikeas** [clausreinke/typescript-tools#59]
$ git clone git://github.com/clausreinke/typescript-tools.git
Cloning into 'typescript-tools'...
remote: Counting objects: 827, done.
remote: Total 827 (delta 0), reused 0 (delta 0), pack-reused 827
Receiving objects: 100% (827/827), 2.86 MiB | 690.00 KiB/s, done.
Resolving deltas: 100% (539/539), done.
Checking connectivity... done.
$ cd typescript-tools/
$ find | grep tss
./ftplugin/typescript_tss.vim
./bin/tss.js
./bin/tss
./tss.ts
$ ./bin/tss 

module.js:340
    throw err;
          ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mperdikeas/typescript-tools/bin/tss.js:6:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
$ echo 'the below is to show that Typescript is installed, and what is my system'
the below is to show that Typescript is installed, and what is my system
$ tsc --version
message TS6029: Version 1.6.2
$ which tsc
/home/mperdikeas/.node_modules_global/lib/node_modules/typescript/bin/tsc
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by sameera207** [comment]
@mperdikeas , do u have `typescript` installed ? if not  do 

`npm install -g typescript`

**Comment by mperdikeas** [comment]
@sameera207 

See the following trace: 

````$ sudo npm install -g typescript
npm http GET https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/typescript
/home/mperdikeas/.node_modules_global/bin/tsserver -> /home/mperdikeas/.node_modules_global/lib/node_modules/typescript/bin/tsserver
/home/mperdikeas/.node_modules_global/bin/tsc -> /home/mperdikeas/.node_modules_global/lib/node_modules/typescript/bin/tsc
typescript@1.6.2 /home/mperdikeas/.node_modules_global/lib/node_modules/typescript
mperdikeas@beorn:~/typescript-tools/bin#
$ echo $?
0
mperdikeas@beorn:~/typescript-tools/bin#
$ ./tss 

module.js:340
    throw err;
          ^
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/mperdikeas/typescript-tools/bin/tss.js:6:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

**Comment by clausreinke** [comment]
Having a globally installed `tsc` is *not* the same as having a locally installed, importable `typescript` module. `node` is complaining about the latter. Please read the instructions again - you're missing an install step.

**Comment by clausreinke** [comment]
PS. if you really want to run `bin/tss`, instead of a global `tss`, you need to run `npm install` in `typescript-tools`, not `npm install -g`

**Comment by wizelements** [comment]
`npm install typescript-tools --save-dev` fixed my issue

**Comment by amaziagur** [comment]
for some reason `npm install typescript --save-dev` did the trick for me, can't say i can explain why..

**Comment by NanciBotelho** [comment]
I was having the same issue and `npm install typescript` fixed it.

**Comment by overcomer79** [comment]
In some case, you need to have typescript installed locally when it is used from an external module. (e.g. tsc-watch) so: 
`npm install typescript --save-dev` 
or
`npm install typescript --save`
depending from your needs.

**Comment by RenukaTh** [comment]
I have installed typescript. 
Still i am facing the issue.




Error: Cannot find module 'D:\GTMAUTOMATION\node_modules\typescript\bin\tsc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protractorpoc@1.0.0 pretest: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protractorpoc@1.0.0 pretest script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\495211\AppData\Roaming\npm-cache\_logs\2019-08-22T10_01_13_284Z-debug.log
PS D:\GTMAUTOMATION> npm install typescript --save
npm WARN registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/typescript failed, reason: getaddrinfo ENOTFOUND proxy.company.com proxy.company.com:8080
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:

**Comment by tmdwo5811** [comment]
> for some reason `npm install typescript --save-dev` did the trick for me, can't say i can explain why..

**Comment by shrikanthsp22** [comment]
can anybody please suggest a soultion for this? 
Context : I upgraded a project from angular version 5.2 to 11 and typescript is installed . im using node version 11.2. and im still facing the issue-  throw new Error('Could not find local "typescript" package.'

Kindly help

**Comment by ambujkhanna** [comment]
I have upgraded my Angular 8 project to Angular 11 and I am start facing this issue with my server.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle server@1.0.0~prestart: server@1.0.0
6 info lifecycle server@1.0.0~start: server@1.0.0
7 verbose lifecycle server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle server@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Ambuj Khanna\Projects\angular_mgration_R&D\STAConsole\server\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Users\10064213\AppData\Local\Microsoft\WindowsApps;C:\Users\10064213\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\10064213\AppData\Local\GitHubDesktop\bin;C:\Users\10064213\.dotnet\tools;C:\Users\10064213\AppData\Roaming\npm
9 verbose lifecycle server@1.0.0~start: CWD: C:\Ambuj Khanna\Projects\angular_mgration_R&D\STAConsole\server
10 silly lifecycle server@1.0.0~start: Args: [ '/d /s /c', 'gulp start' ]
11 silly lifecycle server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle server@1.0.0~start: Failed to exec start script
13 verbose stack Error: server@1.0.0 start: `gulp start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid server@1.0.0
15 verbose cwd C:\Ambuj Khanna\Projects\angular_mgration_R&D\STAConsole\server
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.22.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error server@1.0.0 start: `gulp start`
22 error Exit status 1
23 error Failed at the server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
